markdown: kramdown
theme: minima
plugins: 
  - jekyll-sitemap
kramdown:
  input: GFM
  hard_wrap: false
title: コミトク：Kindle本のセール・高還元情報まとめサイト
description: Kindle本のセール・高還元情報まとめ
timezone: Asia/Tokyo
github:
  is_project_page: true
