name: daily-pages

on:
  schedule:
    # JST 04:00（UTC 19:00）
    - cron: "0 19 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
        
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      # PAAPIのモジュールを認識させるのに必要
      # - name: Set PYTHONPATH
      #   run: |
      #     export PYTHONPATH=$(pwd):$PYTHONPATH
      #     echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Generate docs via output.py
        env:
          PAAPI_ACCESS_KEY: ${{ secrets.PAAPI_ACCESS_KEY }}
          PAAPI_SECRET_KEY: ${{ secrets.PAAPI_SECRET_KEY }}
          PAAPI_ASSOCIATE_TAG: ${{ secrets.PAAPI_ASSOCIATE_TAG }}
        run: |
          python modules/output_api_search_keyword.py
          python modules/create_md_table.py
          python output.py

      - name: Commit & Push
        shell: bash
        run: |
          set -euo pipefail
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/index.md
            MSG_NOW=$(TZ=Asia/Tokyo date '+%Y-%m-%d %H:%M:%S %Z')
            git commit -m "chore: update time (${MSG_NOW}) [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
